services:
  - type: web
    name: ai-fraud-detection-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
